#ifndef FEX_THUNKLIBS_LIBGL_ANDROID_GL_PROC_LIST_H
#define FEX_THUNKLIBS_LIBGL_ANDROID_GL_PROC_LIST_H

// Shared Android GL proc surface used by the guest-side lookup tables.
// Keep this list in sync with the Android-facing libGL thunk surface.
#define FEX_ANDROID_GL_PROC_LIST(OP) \
  OP(glGetString) \
  OP(glGetStringi) \
  OP(glClear) \
  OP(glClearColor) \
  OP(glViewport) \
  OP(glEnable) \
  OP(glDisable) \
  OP(glBlendFunc) \
  OP(glBlendFuncSeparate) \
  OP(glBlendEquation) \
  OP(glColorMask) \
  OP(glDepthFunc) \
  OP(glDepthMask) \
  OP(glScissor) \
  OP(glStencilFunc) \
  OP(glStencilMask) \
  OP(glStencilOp) \
  OP(glCullFace) \
  OP(glFrontFace) \
  OP(glCreateShader) \
  OP(glDeleteShader) \
  OP(glShaderSource) \
  OP(glCompileShader) \
  OP(glGetShaderiv) \
  OP(glGetShaderInfoLog) \
  OP(glCreateProgram) \
  OP(glDeleteProgram) \
  OP(glAttachShader) \
  OP(glDetachShader) \
  OP(glLinkProgram) \
  OP(glUseProgram) \
  OP(glGetProgramiv) \
  OP(glGetProgramInfoLog) \
  OP(glBindAttribLocation) \
  OP(glGetActiveAttrib) \
  OP(glGetActiveUniform) \
  OP(glGetUniformBlockIndex) \
  OP(glGetUniformLocation) \
  OP(glGetAttribLocation) \
  OP(glUniform1i) \
  OP(glUniform1f) \
  OP(glUniform1fv) \
  OP(glUniform2f) \
  OP(glUniform3f) \
  OP(glUniform4f) \
  OP(glUniform4fv) \
  OP(glUniformBlockBinding) \
  OP(glUniformMatrix2fv) \
  OP(glUniformMatrix3fv) \
  OP(glUniformMatrix4fv) \
  OP(glGenBuffers) \
  OP(glDeleteBuffers) \
  OP(glBindBuffer) \
  OP(glBindBufferRange) \
  OP(glBindVertexBuffer) \
  OP(glBufferData) \
  OP(glBufferStorage) \
  OP(glBufferSubData) \
  OP(glMapBufferRange) \
  OP(glUnmapBuffer) \
  OP(glGenVertexArrays) \
  OP(glDeleteVertexArrays) \
  OP(glGenVertexArraysAPPLE) \
  OP(glDeleteVertexArraysAPPLE) \
  OP(glBindVertexArray) \
  OP(glBindVertexArrayAPPLE) \
  OP(glVertexAttribBinding) \
  OP(glVertexAttribFormat) \
  OP(glVertexAttribPointer) \
  OP(glEnableVertexAttribArray) \
  OP(glDisableVertexAttribArray) \
  OP(glGetVertexAttribiv) \
  OP(glGenTextures) \
  OP(glDeleteTextures) \
  OP(glBindTexture) \
  OP(glTexImage2D) \
  OP(glTexSubImage2D) \
  OP(glTexParameteri) \
  OP(glTexParameterf) \
  OP(glTexStorage2D) \
  OP(glGetTexParameteriv) \
  OP(glCompressedTexImage2D) \
  OP(glActiveTexture) \
  OP(glGenerateMipmap) \
  OP(glGenFramebuffers) \
  OP(glDeleteFramebuffers) \
  OP(glBindFramebuffer) \
  OP(glFramebufferTexture2D) \
  OP(glInvalidateFramebuffer) \
  OP(glCheckFramebufferStatus) \
  OP(glBlitFramebuffer) \
  OP(glBlitFramebufferEXT) \
  OP(glGenRenderbuffers) \
  OP(glDeleteRenderbuffers) \
  OP(glBindRenderbuffer) \
  OP(glRenderbufferStorage) \
  OP(glRenderbufferStorageMultisample) \
  OP(glRenderbufferStorageMultisampleEXT) \
  OP(glFramebufferRenderbuffer) \
  OP(glGenSamplers) \
  OP(glDeleteSamplers) \
  OP(glBindSampler) \
  OP(glSamplerParameterf) \
  OP(glSamplerParameteri) \
  OP(glDrawArrays) \
  OP(glDrawElements) \
  OP(glDrawArraysInstanced) \
  OP(glDrawElementsInstanced) \
  OP(glFenceSync) \
  OP(glClientWaitSync) \
  OP(glDeleteSync) \
  OP(glGetError) \
  OP(glGetBooleanv) \
  OP(glGetIntegerv) \
  OP(glGetFloatv) \
  OP(glIsBuffer) \
  OP(glIsFramebuffer) \
  OP(glIsProgram) \
  OP(glIsRenderbuffer) \
  OP(glIsSampler) \
  OP(glIsShader) \
  OP(glIsVertexArray) \
  OP(glIsVertexArrayAPPLE) \
  OP(glObjectLabel) \
  OP(glPushDebugGroup) \
  OP(glPopDebugGroup) \
  OP(glPushGroupMarkerEXT) \
  OP(glPopGroupMarkerEXT) \
  OP(glPixelStorei) \
  OP(glDisableClientState)

#define FEX_ANDROID_GL_PROC_LIST_FOR_THUNKGEN(OP) \
  OP(glGetString) \
  OP(glGetStringi) \
  OP(glClear) \
  OP(glClearColor) \
  OP(glViewport) \
  OP(glEnable) \
  OP(glDisable) \
  OP(glBlendFunc) \
  OP(glBlendFuncSeparate) \
  OP(glBlendEquation) \
  OP(glColorMask) \
  OP(glDepthFunc) \
  OP(glDepthMask) \
  OP(glScissor) \
  OP(glStencilFunc) \
  OP(glStencilMask) \
  OP(glStencilOp) \
  OP(glCullFace) \
  OP(glFrontFace) \
  OP(glCreateShader) \
  OP(glDeleteShader) \
  OP(glCompileShader) \
  OP(glGetShaderiv) \
  OP(glGetShaderInfoLog) \
  OP(glCreateProgram) \
  OP(glDeleteProgram) \
  OP(glAttachShader) \
  OP(glDetachShader) \
  OP(glLinkProgram) \
  OP(glUseProgram) \
  OP(glGetProgramiv) \
  OP(glGetProgramInfoLog) \
  OP(glBindAttribLocation) \
  OP(glGetActiveAttrib) \
  OP(glGetActiveUniform) \
  OP(glGetUniformBlockIndex) \
  OP(glGetUniformLocation) \
  OP(glGetAttribLocation) \
  OP(glUniform1i) \
  OP(glUniform1f) \
  OP(glUniform1fv) \
  OP(glUniform2f) \
  OP(glUniform3f) \
  OP(glUniform4f) \
  OP(glUniform4fv) \
  OP(glUniformBlockBinding) \
  OP(glUniformMatrix2fv) \
  OP(glUniformMatrix3fv) \
  OP(glUniformMatrix4fv) \
  OP(glGenBuffers) \
  OP(glDeleteBuffers) \
  OP(glBindBuffer) \
  OP(glBindBufferRange) \
  OP(glBindVertexBuffer) \
  OP(glBufferData) \
  OP(glBufferStorage) \
  OP(glBufferSubData) \
  OP(glMapBufferRange) \
  OP(glUnmapBuffer) \
  OP(glGenVertexArrays) \
  OP(glDeleteVertexArrays) \
  OP(glGenVertexArraysAPPLE) \
  OP(glDeleteVertexArraysAPPLE) \
  OP(glBindVertexArray) \
  OP(glBindVertexArrayAPPLE) \
  OP(glVertexAttribBinding) \
  OP(glVertexAttribFormat) \
  OP(glVertexAttribPointer) \
  OP(glEnableVertexAttribArray) \
  OP(glDisableVertexAttribArray) \
  OP(glGetVertexAttribiv) \
  OP(glGenTextures) \
  OP(glDeleteTextures) \
  OP(glBindTexture) \
  OP(glTexImage2D) \
  OP(glTexSubImage2D) \
  OP(glTexParameteri) \
  OP(glTexParameterf) \
  OP(glTexStorage2D) \
  OP(glGetTexParameteriv) \
  OP(glCompressedTexImage2D) \
  OP(glActiveTexture) \
  OP(glGenerateMipmap) \
  OP(glGenFramebuffers) \
  OP(glDeleteFramebuffers) \
  OP(glBindFramebuffer) \
  OP(glFramebufferTexture2D) \
  OP(glInvalidateFramebuffer) \
  OP(glCheckFramebufferStatus) \
  OP(glBlitFramebuffer) \
  OP(glBlitFramebufferEXT) \
  OP(glGenRenderbuffers) \
  OP(glDeleteRenderbuffers) \
  OP(glBindRenderbuffer) \
  OP(glRenderbufferStorage) \
  OP(glRenderbufferStorageMultisample) \
  OP(glRenderbufferStorageMultisampleEXT) \
  OP(glFramebufferRenderbuffer) \
  OP(glGenSamplers) \
  OP(glDeleteSamplers) \
  OP(glBindSampler) \
  OP(glSamplerParameterf) \
  OP(glSamplerParameteri) \
  OP(glDrawArrays) \
  OP(glDrawElements) \
  OP(glDrawArraysInstanced) \
  OP(glDrawElementsInstanced) \
  OP(glFenceSync) \
  OP(glClientWaitSync) \
  OP(glDeleteSync) \
  OP(glGetError) \
  OP(glGetBooleanv) \
  OP(glGetIntegerv) \
  OP(glGetFloatv) \
  OP(glIsBuffer) \
  OP(glIsFramebuffer) \
  OP(glIsProgram) \
  OP(glIsRenderbuffer) \
  OP(glIsSampler) \
  OP(glIsShader) \
  OP(glIsVertexArray) \
  OP(glIsVertexArrayAPPLE) \
  OP(glObjectLabel) \
  OP(glPushDebugGroup) \
  OP(glPopDebugGroup) \
  OP(glPushGroupMarkerEXT) \
  OP(glPopGroupMarkerEXT) \
  OP(glPixelStorei) \
  OP(glDisableClientState)

#ifdef BUILD_ANDROID
extern "C" {
void glBindVertexArrayAPPLE(GLuint array);
void glDeleteVertexArraysAPPLE(GLsizei n, const GLuint* arrays);
void glGenVertexArraysAPPLE(GLsizei n, GLuint* arrays);
GLboolean glIsVertexArrayAPPLE(GLuint array);
void glBlitFramebufferEXT(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1,
                          GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1,
                          GLbitfield mask, GLenum filter);
void glRenderbufferStorageMultisampleEXT(GLenum target, GLsizei samples, GLenum internalformat,
                                         GLsizei width, GLsizei height);
void glPushGroupMarkerEXT(GLsizei length, const GLchar* marker);
void glPopGroupMarkerEXT(void);
}
#endif

#endif
